#!/bin/bash

# This script is for installing go inside of minikube for testing

command -v /usr/local/go/bin/go
if [ $? == 0 ]
then
  exit 0;
fi

curl -L -o go1.19.10.linux-amd64.tar.gz https://go.dev/dl/go1.19.10.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.10.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin

