name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make static-linux

  # build-deb:
  #   if: ${{ github.event_name == 'release' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.20'

  #   - name: Build
  #     run: make deb

  # build-rpm:
  #   if: ${{ github.event_name == 'release' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.20'

  #   - name: Build
  #     run: make rpm

  build-arm:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make cross-arm

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make cross-win

  build-mac:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make cross-mac

  upload:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: [build-linux, build-deb, build-rpm, build-windows, build-mac, build-arm]
    steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cri-dockerd
        retention-days: 5
        path: |
          packaging/deb/**/**/**/*.deb
          packaging/rpm/**/**/**/*.rpm
          packaging/static/**/**/**/*.tgz
          packaging/static/**/**/**/*.zip
