name: Publish

on:
  workflow_run:
    workflows: [Build, End-to-End Tests, Integration Tests]
    types:
      - completed

jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packaging/deb/**/**/**/*.deb
            packaging/rpm/**/**/**/*.rpm
            packaging/static/**/**/**/*.tgz
            packaging/static/**/**/**/*.zip
