name: Publish

on:
  workflow_call:

jobs:
  publish-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1
      - name: Push binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packaging/deb/**/**/**/*.deb
            packaging/rpm/**/**/**/*.rpm
            packaging/static/**/**/**/*.tgz
            packaging/static/**/**/**/*.zip
